various updates

diff --git a/.local/bin/tools/cuesplit b/.local/bin/tools/cuesplit
--- a/.local/bin/tools/cuesplit
+++ b/.local/bin/tools/cuesplit
@@ -1,78 +1,74 @@
 #!/bin/sh
+# Based on the script from the Arch Forums
 # https://bbs.archlinux.org/viewtopic.php?id=75774
 
 # frontend for: cuetools, shntool, mp3splt
 # optional dependencies: flac, mac, wavpack, ttaenc
 # v1.3 sen
 
-SDIR=$(pwd)
-
-if [ "$1" = "" ]; then
-	DIR=$SDIR
+if [ -z "$1" ]; then
+	DIR=$PWD
 else
 	case $1 in
 		-h|--help)
-			echo "Usage: cuesplit [Path]"
-			echo "The default path is the current directory."
+			printf "Usage: cuesplit [Path]
+				\r* The default path is the current directory.\n"
 			exit
 		;;
 		*)
 			DIR=$1
+		;;
 	esac
 fi
 
-printf '%s' "\
+printf '%s\n---\n' "Searchig for files to split in \`$DIR\` directory..."
 
-Directory: $DIR
-________________________________________
-"
-cd "$DIR"
+cd "$DIR" || return
 TYPE=$(ls -t1)
 
 case $TYPE in
-	*.ape)
-		mkdir split
-		shnsplit -d split -f *.cue -o "flac flac -V --best -o %f -" *.ape -t "%n %p - %t"
+	*.ape*)
+		mkdir -p split
+		shnsplit -d split -f ./*.cue -o "flac flac -V --best -o %f -" ./*.ape -t "%n %p - %t"
 		rm -f split/00*pregap*
-		cuetag.sh *.cue split/*.flac
+		cuetag.sh ./*.cue split/*.flac
 	;;
-	*.flac)
-		mkdir split
-		shnsplit -d split -f *.cue -o "flac flac -V --best -o %f -" *.flac -t "%n %p - %t"
+	*.flac*)
+		mkdir -p split
+		shnsplit -d split -f ./*.cue -o "flac flac -V --best -o %f -" ./*.flac -t "%n %p - %t"
 		rm -f split/00*pregap*
-		cuetag.sh *.cue split/*.flac
+		cuetag.sh ./*.cue split/*.flac
 	;;
-
-	*.mp3)
-		mp3splt -no "@n @p - @t (split)" -c *.cue *.mp3
-		cuetag.sh *.cue *split\).mp3
+	*.mp3*)
+		mp3splt -no "@n @p - @t (split)" -c ./*.cue ./*.mp3
+		cuetag.sh ./*.cue ./*split\).mp3
 	;;
-	*.ogg)
-		mp3splt -no "@n @p - @t (split)" -c *.cue *.ogg
-		cuetag.sh *.cue *split\).ogg
+	*.ogg*)
+		mp3splt -no "@n @p - @t (split)" -c ./*.cue ./*.ogg
+		cuetag.sh ./*.cue ./*split\).ogg
 	;;
-	*.tta)
-		mkdir split
-		shnsplit -d split -f *.cue -o "flac flac -V --best -o %f -" *.tta -t "%n %p - %t"
+	*.tta*)
+		mkdir -p split
+		shnsplit -d split -f ./*.cue -o "flac flac -V --best -o %f -" ./*.tta -t "%n %p - %t"
 		rm -f split/00*pregap*
-		cuetag.sh *.cue split/*.flac
+		cuetag.sh ./*.cue split/*.flac
 	;;
-	*.wv)
-		mkdir split
-		shnsplit -d split -f *.cue -o "flac flac -V --best -o %f -" *.wv -t "%n %p - %t"
+	*.wv*)
+		mkdir -p split
+		shnsplit -d split -f ./*.cue -o "flac flac -V --best -o %f -" ./*.wv -t "%n %p - %t"
 		rm -f split/00*pregap*
-		cuetag.sh *.cue split/*.flac
+		cuetag.sh ./*.cue split/*.flac
 	;;
-	*.wav)
-		mkdir split
-		shnsplit -d split -f *.cue -o "flac flac -V --best -o %f -" *.wav -t "%n %p - %t"
+	*.wav*)
+		mkdir -p split
+		shnsplit -d split -f ./*.cue -o "flac flac -V --best -o %f -" ./*.wav -t "%n %p - %t"
 		rm -f split/00*pregap*
-		cuetag.sh *.cue split/*.flac
+		cuetag.sh ./*.cue split/*.flac
 	;;
 	*)
-		echo "Error: Found no files to split!"
-		echo "--> APE, FLAC, MP3, OGG, TTA, WV, WAV"
+		printf ">> Error: Found no files* to split!
+			\r>> Supported formats: ape, flac, mp3, ogg, tta, wv, wav\n"
+		exit 1
 	;;
 esac
 
-exit
